version: '3'

services:
  app:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/home/node/app
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    volumes:
      - ./dbdata:/var/lib/mysql
